### PR TITLE
Added delete environ command

### PR DESCRIPTION
**Pull request by sathishvj**
gofabric8 now has a delete environ command.  Similar to the get environ command.

### CODE REVIEW

**Comment by jstrachan** [comment]
ok to test

**Comment by chmouel** [comment]
Just a suggestion, and in general I believe it would be better to squash all the commits in one for the PR than multiple of them, (but I am not used that much to github worlflow so I may be wrong)

**Comment by chmouel** [comment]
Just a suggestion, and in general I believe it would be better to squash all the commits in one for the PR than multiple of them, (but I am not used that much to github workflow so I may be wrong)

**Comment by chmouel** [comment]
reckicked the test since the CI should be working now,

**Comment by jstrachan** [comment]
@chmouel happy to merge?

**Comment by chmouel** [comment]
yep 👍

**Comment by chmouel** [comment]
I believe this can be closed!

**Pull request merged**
