### PR TITLE
Fix linux build (hack)

### PR DESCRIPTION
**Pull request by chmouel**
We need to import this commit :

https://github.com/kubernetes/kubernetes/commit/49201f6923b2a7ba6694ef1ed8db6f9a24e7eb2e

To get the linux build compiled.

Currently the glide dependency is a mess and we can't get that commit in openshift/kubernetes
without some awfull circular dependencies :sadpanda:

For a quick fix we import the patch directly on the sources.

Proper solution would be :

        - Cleanup the depencies.
        - Work with upstream on an openshift origin client like for kube.
        - Restart to a minimal and sane glide.yaml file letting glide do its magic.

### CODE REVIEW

**Comment by chmouel** [comment]
The jenkins error doesn't make sense at all as compiling on my linux box works : 

image

**Comment by chmouel** [comment]
it seems that we have a problem with the build getting the wrong commit id, it supposed to test 92eb2c09 but in the jenkins log it says 3e470f6d : 

image

I tried to replicate the same thing within the same docker image and it compiles fine, so I am guessing it's something to do with the Jenkinsfile : 

image

**Comment by rawlingsj** [comment]
yes it is a problem with the jenkisnfile / shared library https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/goMake.groovy#L29

**Comment by rawlingsj** [comment]
I'll fix it now.

**Comment by rawlingsj** [comment]
[merge]

**Pull request merged**
