### PR TITLE
Remove unnecessary ops on the tempfile

### PR DESCRIPTION
**Pull request by jaseemabid**

### CODE REVIEW

**Comment by chmouel** [comment]
Sounds good, thanks.

**Comment by jaseemabid** [comment]
@chmouel You closed without merging

**Comment by chmouel** [comment]
ah sorry, any ideas why this wasn't passing the CI ?

**Comment by jaseemabid** [comment]
Could be the classic old issue. 

```
Still waiting to schedule task
All nodes of label ‘dockergofabric8_2’ are offline
```

**Comment by jaseemabid** [comment]
These pipelines are shitty and flaky. There is no output from `+ make` :(

**Comment by jaseemabid** [comment]
Rebuild passed.    https://jenkins.cd.test.fabric8.io/job/fabric8_CI/job/gofabric8/job/PR-642/2/console

**Pull request merged**
